//! Writes `examples/config.json` and `examples/keys.txt` from the defaults.
//!
//! The example used to be kept by hand and had drifted: it held 103 of the 110
//! fields, with no `version`, so somebody who copied it wholesale got
//! `version: 0` and both migration steps re-applied to a current file. Written
//! from `Config::default()` it cannot drift again.
//!
//! Run it after adding a field:
//!
//! ```text
//! cargo run --example write_defaults
//! ```

use eframe::egui::Key;

use avis_imgv::config::Config;

fn main() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("examples");

    let config = serde_json::to_string_pretty(&Config::default()).expect("the defaults serialise");
    let path = root.join("config.json");
    std::fs::write(&path, config + "\n").expect("writing the example configuration");
    println!("wrote {}", path.display());

    // The canonical spelling of every key egui can report, so a name copied
    // out of this file is a name the viewer will accept back.
    let mut names: Vec<&str> = Key::ALL.iter().map(|key| key.name()).collect();
    names.sort_unstable();
    names.dedup();

    let keys = format!(
        "# Key names avis-imgv accepts, one per line. Case does not matter.\n\
         #\n\
         # Modifiers: ctrl, alt, shift, cmd, mac_cmd. \"cmd\" is the Command key\n\
         # on macOS and Ctrl everywhere else.\n\
         #\n\
         # Generated by `cargo run --example write_defaults`; do not edit.\n\n{}\n",
        names.join("\n")
    );

    let path = root.join("keys.txt");
    std::fs::write(&path, keys).expect("writing the key names");
    println!("wrote {}", path.display());
}
